// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdcgRuCXVhjUXfFSLLCWlLuhbDwqLWvQ4',
    appId: '1:631392078440:web:a13819fdb01a324d1dc9dd',
    messagingSenderId: '631392078440',
    projectId: 'nfc-learning-2aaa2',
    authDomain: 'nfc-learning-2aaa2.firebaseapp.com',
    databaseURL: 'https://nfc-learning-2aaa2-default-rtdb.firebaseio.com',
    storageBucket: 'nfc-learning-2aaa2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9SpDfGp7tWd9R34j-CVfa4VdHHbq-63w',
    appId: '1:631392078440:android:b0a6a253d3edd81d1dc9dd',
    messagingSenderId: '631392078440',
    projectId: 'nfc-learning-2aaa2',
    databaseURL: 'https://nfc-learning-2aaa2-default-rtdb.firebaseio.com',
    storageBucket: 'nfc-learning-2aaa2.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdcgRuCXVhjUXfFSLLCWlLuhbDwqLWvQ4',
    appId: '1:631392078440:web:79d62ff66a04820c1dc9dd',
    messagingSenderId: '631392078440',
    projectId: 'nfc-learning-2aaa2',
    authDomain: 'nfc-learning-2aaa2.firebaseapp.com',
    databaseURL: 'https://nfc-learning-2aaa2-default-rtdb.firebaseio.com',
    storageBucket: 'nfc-learning-2aaa2.firebasestorage.app',
  );

}