// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfWEtc0H55mmqJtsSCyRPvx4jn-F6ODcI',
    appId: '1:631392078440:web:33bac000c9def5bb1dc9dd',
    messagingSenderId: '631392078440',
    projectId: 'nfc-learning-2aaa2',
    authDomain: 'nfc-learning-2aaa2.firebaseapp.com',
    storageBucket: 'nfc-learning-2aaa2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9SpDfGp7tWd9R34j-CVfa4VdHHbq-63w',
    appId: '1:631392078440:android:86a64a3c383dfa0f1dc9dd',
    messagingSenderId: '631392078440',
    projectId: 'nfc-learning-2aaa2',
    storageBucket: 'nfc-learning-2aaa2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZ_b028n4pcaWzkuoyo19bgP41QV-TeiM',
    appId: '1:631392078440:ios:71630315f6079db21dc9dd',
    messagingSenderId: '631392078440',
    projectId: 'nfc-learning-2aaa2',
    storageBucket: 'nfc-learning-2aaa2.appspot.com',
    iosBundleId: 'com.example.okk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZ_b028n4pcaWzkuoyo19bgP41QV-TeiM',
    appId: '1:631392078440:ios:71630315f6079db21dc9dd',
    messagingSenderId: '631392078440',
    projectId: 'nfc-learning-2aaa2',
    storageBucket: 'nfc-learning-2aaa2.appspot.com',
    iosBundleId: 'com.example.okk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfWEtc0H55mmqJtsSCyRPvx4jn-F6ODcI',
    appId: '1:631392078440:web:e50a8ba1edb4a40b1dc9dd',
    messagingSenderId: '631392078440',
    projectId: 'nfc-learning-2aaa2',
    authDomain: 'nfc-learning-2aaa2.firebaseapp.com',
    storageBucket: 'nfc-learning-2aaa2.appspot.com',
  );
}
