// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCm5WiUdVkNYNlab7t-PmRzpdvrs4F8KA',
    appId: '1:3640803145:web:b5316e982afe4df664a498',
    messagingSenderId: '3640803145',
    projectId: 'nfc-learning',
    authDomain: 'nfc-learning.firebaseapp.com',
    storageBucket: 'nfc-learning.appspot.com',
    measurementId: 'G-KQMCHX901W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBL8JbD2LBYc5shGucx19VncUGfcgqWk14',
    appId: '1:3640803145:android:b3bc14883057102564a498',
    messagingSenderId: '3640803145',
    projectId: 'nfc-learning',
    storageBucket: 'nfc-learning.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCm5WiUdVkNYNlab7t-PmRzpdvrs4F8KA',
    appId: '1:3640803145:web:34ff072d333694ec64a498',
    messagingSenderId: '3640803145',
    projectId: 'nfc-learning',
    authDomain: 'nfc-learning.firebaseapp.com',
    storageBucket: 'nfc-learning.appspot.com',
    measurementId: 'G-Z74Q42XJM3',
  );
}
